name: Transfer Issue & Create Stub
description: A GitHub Action for transferring issues between github repos with the ability to create a stub issue in the original repo.
author: John Ouellet
inputs:
  apply_label:
    description: A label to apply on the new issue in the format "LABEL:HEXCODE"
    default: false
  create_stub:
    description: Create a stub issue with title and description in original repo
    default: false
  allow_private_public_transfer:
    description: Do we allow transferring a private issue to a public repo
    default: false    
  create_labels_if_missing:
    description: Whether to create labels if they don't exist in the target repository (matched by name)
    default: false
  enable_custom_label_routing:
    description:  Make it possible to route labels to any repository of the organization by providing the repository name in the label name
    default: false    
  debug:
    description: Enable debug output
    default: false
  router:
    description: A label to repo routing in the form "LABEL:REPO"
    required: true
  token:
    description: The GitHub Personal Access Token
    required: true
outputs:
  destination_repo:
    description: The name of the destination repo
  new_issue_number:
    description: The number of the new issue
  new_issue_url:
    description: The url of the new issue
  stub_issue_number:
    description: The number of the created issue stub

runs:
  using: docker
  image: Dockerfile
branding:
  color: "purple"
  icon: "arrow-right-circle"
