name: Transfer Issue & Create Stub
description: A GitHub Action for transferring issues between github repos with the ability to create a stub issue in the original repo.
author: John Ouellet
inputs:
  apply_labels:
    description: An array of labels to apply to each issue once transferred
    required: true
  create_stub:
    description: Create a stub issue with title and description in original repo
    default: false
    required: false
  debug:
    description: Enable debug output
    default: true
  router:
    description: An array of label names and repo names
    required: true
  token:
    description: The GitHub Personal Access Token
    required: true
outputs:
  new_issue_number:
    description: The number of the new issue
  new_issue_url:
    description: The url of the new issue
  destination_repo:
    description: The name of the destination repo
runs:
  using: docker
  image: Dockerfile
branding:
  color: "green"
  icon: "arrow-right-circle"
