name: Transfer Issue & Create Stub
description: A GitHub Action for transferring issues between github repos with the ability to create a stub issue in the original repo.
author: John Ouellet
inputs:
  apply_label:
    description: A label to apply on the new issue in the format "LABEL:HEXCODE"
    required: false
  create_stub:
    description: Create a stub issue with title and description in original repo
    default: false
    required: false
  debug:
    description: Enable debug output
    default: true
  router:
    description: A label to repo routing in the form "LABEL:REPO"
    required: true
  token:
    description: The GitHub Personal Access Token
    required: true
outputs:
  destination_repo:
    description: The name of the destination repo
  new_issue_number:
    description: The number of the new issue
  new_issue_url:
    description: The url of the new issue
  stub_issue_number:
    description: The number of the created issue stub
runs:
  using: docker
  image: Dockerfile
branding:
  color: "green"
  icon: "arrow-right-circle"
