name: Test Issue Action
on:
  issues:
    types:
      - labeled

jobs:
  test-action:
    runs-on: ${{ matrix.os }}
    env:
      TERM: xterm
    strategy:
      matrix:
        os:
          - ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Test Action
        id: test_action
        uses: ./
        with:
          token: ${{ secrets.TRANSFER_ISSUE_TOKEN }}
          debug: true
          labels_file_path: '.github/transfer-issue-labels.yml'
          map_repo_labels_file_path: '.github/transfer-issue-map-repo-labels.yml'
      - name: Echo Output Data
        if: steps.test_action.outputs.new_issue_number != ''
        run: |
          echo ${{steps.test_action.outputs.new_issue_number}}
          echo ${{steps.test_action.outputs.new_issue_url}}
          echo ${{steps.test_action.outputs.destination_repo}}

